// quotes.js
window.QUOTES = [
  {
    quote_no: "2014",
    date: "2026-03-04",
    name: "Laura Holtzman",
    email: "Laura.Holtzman@sfband.org",
    phone: "",
    notes: "",
   payload_json: {
  items: [
    {"type":"Product","product":"BC3413","color":"Purple","qty":13,"price":10.94,"sizes":{"M":5,"L":3,"XL":5}},
    {"type":"Product","product":"BC3413","color":"Purple","qty":2,"price":14.94,"sizes":{"3X":2}},
    {"type":"Product","product":"BC3413","color":"Black","qty":16,"price":10.94,"sizes":{"M":3,"L":7,"XL":6}},
    {"type":"Product","product":"BC3413","color":"Black","qty":1,"price":12.94,"sizes":{"2X":1}},
    {"type":"Product","product":"BC3413","color":"Black","qty":3,"price":14.94,"sizes":{"3X":3}},
    {"type":"Product","product":"BC3413","color":"Charcoal Black","qty":14,"price":10.94,"sizes":{"S":1,"M":6,"L":3,"XL":4}},
    {"type":"Product","product":"BC3413","color":"Charcoal Black","qty":1,"price":16.94,"sizes":{"4X":1}},
    {"type":"Product","product":"BC3501","color":"Team Purple","qty":2,"price":10.99,"sizes":{"L":1,"XL":1}},
    {"type":"Product","product":"BC3501","color":"Black","qty":5,"price":10.99,"sizes":{"L":3,"XL":2}},
    {"type":"Product","product":"DT6200","color":"Heathered Charcoal","qty":3,"price":10.20,"sizes":{"M":1,"XL":2}},
    {"type":"Product","product":"DM130L","color":"Black","qty":3,"price":9.16,"sizes":{"M":1,"L":1,"XL":1}},
    {"type":"Product","product":"DM130L","color":"Heathered Charcoal","qty":2,"price":9.16,"sizes":{"M":1,"XL":1}},
    {"type":"Product","product":"DM1350L","color":"Purple Frost","qty":4,"price":10.16,"sizes":{"S":1,"M":1,"L":1,"XL":1}},
    {"type":"Product","product":"DM1350","color":"Purple Frost","qty":4,"price":12.16,"sizes":{"2X":4}},
    {"type":"Product","product":"DM1350L","color":"Black","qty":4,"price":10.16,"sizes":{"S":1,"M":2,"L":1}},
    {"type":"Product","product":"DM1350L","color":"Black","qty":1,"price":12.16,"sizes":{"2X":1}},
    {"type":"Product","product":"DM1350L","color":"Heathered Charcoal","qty":1,"price":10.16,"sizes":{"M":1}},
    {"type":"Product","product":"DT110","color":"Heathered Dusty Sage","qty":1,"price":9.58,"sizes":{"L":1}},
    {"type":"Product","product":"DT110","color":"Heathered Royal","qty":1,"price":9.58,"sizes":{"L":1}},
    {"type":"Product","product":"LPC450VLS","color":"Team Purple","qty":5,"price":9.27,"sizes":{"S":1,"M":1,"L":1,"XL":2}},
    {"type":"Product","product":"DT135","color":"Black","qty":2,"price":9.98,"sizes":{"L":2}},
    {"type":"Product","product":"DT135","color":"Heathered Charcoal","qty":2,"price":9.98,"sizes":{"L":2}},
    {"type":"Product","product":"BC3001Y","color":"Royal Purple","qty":2,"price":8.26,"sizes":{"XS":1,"M":1}},
    {"type":"Product","product":"BC3001Y","color":"Black","qty":2,"price":8.26,"sizes":{"XS":1,"L":1}},
    {"type":"Product","product":"EB2360","color":"Black","qty":1,"price":46.96,"sizes":{"XL":1}},
    {"type":"Product","product":"EB2460","color":"Black","qty":1,"price":55.21,"sizes":{"XL":1}},
    {"type":"Product","product":"EB2460","color":"Black","qty":1,"price":59.21,"sizes":{"3X":1}},
    {"type":"Product","product":"EB2470","color":"Black","qty":5,"price":55.21,"sizes":{"L":3,"XL":2}},
    {"type":"Product","product":"EB531","color":"Black","qty":4,"price":92.10,"sizes":{"M":1,"L":1,"XL":2}},
    {"type":"Product","product":"EB532","color":"Black","qty":6,"price":92.91,"sizes":{"S":1,"L":3,"XL":2}},
    {"type":"Product","product":"EB533","color":"Black","qty":4,"price":92.91,"sizes":{"M":1,"XL":3}},
    {"type":"Product","product":"EB533","color":"","qty":1,"price":94.91,"sizes":{"2X":1}},
    {"type":"Product","product":"EB544","color":"Black","qty":2,"price":84.93,"sizes":{"M":1,"L":1}},
    {"type":"Product","product":"EB545","color":"Black","qty":2,"price":84.93,"sizes":{"XL":2}},
    {"type":"Product","product":"EB533","color":"Black","qty":1,"price":98.91,"sizes":{"4X":1}},
    {"type":"Services","product":"Printing for Shirts","color":"","qty":94,"price":12.30,"sizes":{}},
    {"type":"Services","product":"Embroidery","color":"","qty":28,"price":12.00,"sizes":{}},
    {"type":"Services","product":"Digitizing","color":"","qty":2,"price":30.00,"sizes":{}},
    {"type":"Discount","product":"EB544 - Wrong Size Received - Credit","color":"","qty":1,"price":92.89,"sizes":{}}
   ]
}

